server/django-web-server/rest_portal/documents/urls.py
from django.conf.urls import patterns, url, include

from documents import views

urlpatterns = patterns('',

	# REST interface for documents management
    url(r'^$', views.listUserDocumentsREST.as_view(), name='listuserdocuments'),
    url(r'^(?P<docID>[0-9]*)/$', views.DocumentREST.as_view(), name='documentrest'),
    url(r'^(?P<docID>[0-9]*)/(?P<partID>[0-9]*)/$', views.DocumentPartREST.as_view(), name='documentpartrest'),
    
)

server/django-web-server/rest_portal/rest_portal/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',

	# REST web authentication
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	
	# Django administration site
    url(r'^admin/', include(admin.site.urls)),
    
    # User management and main web application
    url(r'^', include('users.urls', namespace='users')),
    
    # Documents management
    url(r'^rest/docs/', include('documents.urls', namespace='documents')),
)

server/django-web-server/rest_portal/users/urls.py
from django.conf.urls import patterns, url, include

from users import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    
    # Account management
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
    
    # System wide operations
    url(r'^init/$', views.initSystem, name='init'),
    url(r'^levels/$', views.manageLevels, name='levels'),
    
    # User management
    url(r'^users/create/$', views.createUser, name='createuser'),
    url(r'^users/delete/$', views.deleteUser, name='deleteuser'),
    url(r'^users/perm/$', views.manageUserPermissions, name='userpermissions'),
    
    # REST interface for user management
    url(r'^rest/credential/$', views.credentialREST.as_view(), name='restcredential'),
    url(r'^rest/users/(?P<username>[a-zA-Z@.+-_]*)/$', views.userDSAPublicKeyREST.as_view(), name='restuserdsakey'),
    url(r'^rest/levels/$', views.listUserLevelsREST.as_view(), name='restuserlevellist'),
    url(r'^rest/levels/(?P<level>[0-9]*)/$', views.userLevelREST.as_view(), name='restuserlevel'),
)

server/django-web-server/rest_portal/users/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Credential(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True)
	
	pubKey = models.FileField(upload_to='users/pubkeys')
	wrappedPrivKey = models.FileField(upload_to='users/wrappedprivkeys')
	iv = models.FileField(upload_to='users/ivs')
	salt = models.FileField(upload_to='users/salt')
	
	pubDSAKey = models.FileField(upload_to='users/pubDSAkeys')
	wrappedPrivDSAKey = models.FileField(upload_to='users/wrappedprivDSAkeys')
	ivDSA = models.FileField(upload_to='users/ivsDSA')
	saltDSA = models.FileField(upload_to='users/saltDSA')
	
	def __unicode__(self):  # Python 3: def __str__(self):
		return str(self.user)

class Level(models.Model):
	levNumber = models.IntegerField(unique=True)
	
	def __unicode__(self):  # Python 3: def __str__(self):
		return str(self.levNumber)

class UserLevel(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	level = models.ForeignKey(Level, on_delete=models.CASCADE)
	cryptedAESKey = models.FileField(upload_to='levels/cryptedaeskeys')
	
	def __unicode__(self):  # Python 3: def __str__(self):
		return str('Level ' + str(self.level) + ' for user ' + str(self.user))
	
	class Meta:
		unique_together = ('user', 'level')



# Serialization classes
# They should be transient class models
class SerializedCredential(models.Model):
	username = models.CharField(max_length=30)
	
	pubKeyBase64 = models.CharField(max_length=4096)
	wrappedPrivKeyBase64 = models.CharField(max_length=4096)
	ivBase64 = models.CharField(max_length=4096)
	saltBase64 = models.CharField(max_length=4096)
	
	pubDSAKeyBase64 = models.CharField(max_length=4096)
	wrappedPrivDSAKeyBase64 = models.CharField(max_length=4096)
	ivDSABase64 = models.CharField(max_length=4096)
	saltDSABase64 = models.CharField(max_length=4096)

class SerializedUserLevel(models.Model):
	username = models.CharField(max_length=30)
	level = models.IntegerField()
	
	cryptedAESKeyBase64 = models.CharField(max_length=4096)

class SerializedUserPublicDSAKey(models.Model):
	username = models.CharField(max_length=30)
	pubDSAKeyBase64 = models.CharField(max_length=4096)

server/django-web-server/rest_portal/users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.conf import settings

import django.contrib.auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

from django.core.files.base import ContentFile

from py4j.java_gateway import JavaGateway, Py4JNetworkError

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions

import base64

from users import models
from users import serializers



"""
Can't understand if Django closes files automatically or not.
In case of 'IOError: [Errno 24] Too many open files' error
try closing every FileField opened with read() method.
For example:
pubKey = credential.pubKey.read()
credential.pubKey.file.close()
"""



# These are not views!
def getLevelsID(user):
	"""
	Query explaination:
	From Level objects set, get the subset of objects which are ForeignKey in UserLevel objects set that has user as User field.
	Then from this Level objects subset extract levNumber field and construct an ordered list of them
	"""
	return models.Level.objects.filter(userlevel__user=user).values_list('levNumber', flat=True).order_by('levNumber')

def getMaxLevelID(user):
	levels = getLevelsID(user)
	return max(levels)

def getMinUpdateLevel(currentUser, targetUser):
	if currentUser.is_superuser:
		return 0
	else:
		return getMaxLevelID(targetUser)

def getOtherUsersList(user):
	"""
	Query explaination:
	From User objects set, get the subset of objects which have is_superuser attribute False and exclude the object which username is user.username.
	Then from this User objects subset extract username field and construct an ordered list of them
	"""
	return get_user_model().objects.filter(is_superuser=False).exclude(username=user.username).values_list('username', flat=True).order_by('username')

def delUserObjects(userobj):
	credentialobj = models.Credential.objects.get(user=userobj)
	userlevelobjs = models.UserLevel.objects.filter(user=userobj)
	
	# Remove all files
	for u in userlevelobjs:
		u.cryptedAESKey.delete(save=True)
	credentialobj.pubKey.delete(save=False)
	credentialobj.wrappedPrivKey.delete(save=False)
	credentialobj.iv.delete(save=False)
	credentialobj.salt.delete(save=False)
	credentialobj.pubDSAKey.delete(save=False)
	credentialobj.wrappedPrivDSAKey.delete(save=False)
	credentialobj.ivDSA.delete(save=False)
	credentialobj.saltDSA.delete(save=False)
	credentialobj.save()
	
	# Remove objects
	userobj.delete()
	# CASCADE will do the rest ;)



# Views

def index(request):
	initialized = True if models.Credential.objects.all() else False
	content = {
				'user': request.user,
				'initialized': initialized
	}
	return render(request, 'users/home.html', content)



@login_required
def initSystem(request):
	if request.method == 'GET':
		
		if models.Credential.objects.all() or not request.user.is_superuser:
			return HttpResponseRedirect(reverse('users:index'))
		
		if request.user.is_superuser:
			return render(request, 'users/init_system.html', {'user': request.user})
		
	elif request.method == 'POST' and request.user.is_superuser and not models.Credential.objects.all():
		
		# Retrieve components for personal keyring
		username = request.user.username
		password = request.POST['password']
		salt = settings.KEYRING_SALT
		
		# Check if password is correct
		user = django.contrib.auth.authenticate(username=username, password=password)
		if user is None:
			return render(request, 'users/init_system.html', {'error_message': 'Invalid password'})
		
		# Get Java interface
		# Remember to start JVM server first!!!
		gateway = JavaGateway()
		
		javaObject = gateway.entry_point.getObject()
		
		# Get keys element
		userpubkey = javaObject.getPublicKey()
		#userprivkey = javaObject.getPrivateKey()
		#wraparray = javaObject.wrapPrivateRSAKey(userprivkey, username, password, salt)
		wraparray = javaObject.getWrappedRSAPrivKey(username, password, salt)
		userivwrappedkey = wraparray[0]
		userwrappedkey = wraparray[1]
		
		userpubdsakey = javaObject.getDSAPublicKey()
		#userprivdsakey = javaObject.getDSAPrivateKey()
		#wraparraydsa = javaObject.wrapPrivateDSAKey(userprivdsakey, username, password, salt)
		wraparraydsa = javaObject.getWrappedDSAPrivKey(username, password, salt)
		userivwrappedsakey = wraparraydsa[0]
		userwrappeddsakey = wraparraydsa[1]
		
		# Save keyring
		credential = models.Credential()
		
		credential.user = user
		
		credential.pubKey.save(user.username, ContentFile(userpubkey), save=False)
		credential.wrappedPrivKey.save(user.username, ContentFile(userwrappedkey), save=False)
		credential.iv.save(user.username, ContentFile(userivwrappedkey), save=False)
		credential.salt.save(user.username, ContentFile(salt), save=False)
		
		credential.pubDSAKey.save(user.username, ContentFile(userpubdsakey), save=False)
		credential.wrappedPrivDSAKey.save(user.username, ContentFile(userwrappeddsakey), save=False)
		credential.ivDSA.save(user.username, ContentFile(userivwrappedsakey), save=False)
		credential.saltDSA.save(user.username, ContentFile(salt), save=False)
		
		credential.save()
		
		# Create authorization levels
		for i in range(0,4):
			
			javaObject.renewAES()
			levAESKey = javaObject.getAESKey()
			levEncryptedAESKey = javaObject.wrapAESWithRSA(levAESKey, userpubkey)
			
			lev = models.Level()
			
			lev.levNumber = i
			lev.save()
			# Refetch object from DB now that it was saved (dunno if necessary)
			lev = models.Level.objects.get(levNumber=i)
			
			userLev = models.UserLevel()
			userLev.user = user
			userLev.level = lev
			userLev.cryptedAESKey.save(user.username + '_' + str(i), ContentFile(levEncryptedAESKey), save=False)
			
			userLev.save()
			
	return HttpResponseRedirect(reverse('users:index'))



@login_required
def manageLevels(request):
	# Return on home page if system was not initialized
	if not models.Credential.objects.all():
		return HttpResponseRedirect(reverse('users:index'))
	
	if request.method == 'GET' and request.user.is_superuser:
		
		maxLevel = getMaxLevelID(request.user)
		content = {
					'user': request.user,
					'maxlevel': maxLevel,
					'page': 'home'
		}
		return render(request, 'users/manage_levels.html', content)
		
	elif request.method == 'POST' and request.user.is_superuser:
		if request.POST['action'] == 'next':
			
			### Render adding page ###
			
			newLevel = request.POST['level']
			password = request.POST['password']
			
			if newLevel == '':
				maxLevel = getMaxLevelID(request.user)
				content = {
							'user': request.user,
							'page': 'home',
							'maxlevel': maxLevel,
							'error_message': 'Invalid level number'
				}
				return render(request, 'users/manage_levels.html', content)
			
			if not int(newLevel) in range(0,101):
				maxLevel = getMaxLevelID(request.user)
				content = {
							'user': request.user,
							'maxlevel': maxLevel,
							'page': 'home',
							'error_message': 'You must type a value between 0 and 100'
				}
				return render(request, 'users/manage_levels.html', content)
			
			content = {
						'user': request.user,
						'page': 'confirmation',
						'password': password,
						'newlevel': newLevel
			}
			return render(request, 'users/manage_levels.html', content)
		
		elif request.POST['action'] == 'confirm':
			
			### Add new level (if possible) ###
			
			# Fetch required elements from POST
			newLevelNumber = request.POST['newlevel']
			if newLevelNumber == '':
				maxLevel = getMaxLevelID(request.user)
				content = {
							'user': request.user,
							'page': 'home',
							'maxlevel': maxLevel,
							'error_message': 'Invalid level number'
				}
				return render(request, 'users/manage_levels.html', content)
			
			if not int(newLevelNumber) in range(0,101):
				maxLevel = getMaxLevelID(request.user)
				content = {
							'user': request.user,
							'maxlevel': maxLevel,
							'page': 'home',
							'error_message': 'You must type a value between 0 and 100'
				}
				return render(request, 'users/manage_levels.html', content)
			
			newLevelNumber = int(newLevelNumber)
			
			username = request.user.username
			password = request.POST['password']
			
			# Check password
			user = django.contrib.auth.authenticate(username=username, password=password)
			if user is None:
				maxLevel = getMaxLevelID(request.user)
				content = {
							'user': request.user,
							'page': 'home',
							'maxlevel': maxLevel,
							'error_message': 'Invalid password'
				}
				return render(request, 'users/manage_levels.html', content)
			
			# Check if level is equal
			currentLevel = getMaxLevelID(request.user)
			if currentLevel == newLevelNumber:
				maxLevel = getMaxLevelID(request.user)
				content = {
							'user': request.user,
							'page': 'home',
							'maxlevel': maxLevel,
							'error_message': 'You have chosen the same level'
				}
				return render(request, 'users/manage_levels.html', content)
			
			if newLevelNumber > currentLevel:
				
				### Add all levels from currentLevel+1 to newLevelNumber ###
				
				# Get user credentials
				credential = models.Credential.objects.get(user=user)
				
				# Get Java interface
				# Remember to start JVM server first!!!
				gateway = JavaGateway()
				javaObject = gateway.entry_point.getObject()
				
				# Get keys
				pubKey = credential.pubKey.read()
				privKey = credential.wrappedPrivKey.read()
				iv = credential.iv.read()
				salt = credential.salt.read()
				
				# Need to use Java arrays objects in order to call java method
				pubKeyArray = gateway.new_array(gateway.jvm.byte, len(pubKey))
				for i in range(0,len(pubKey)):
					pubKeyArray[i] = pubKey[i]
				
				privKeyArray = gateway.new_array(gateway.jvm.byte, len(privKey))
				for i in range(0,len(privKey)):
					privKeyArray[i] = privKey[i]
				
				ivArray = gateway.new_array(gateway.jvm.byte, len(iv))

server/django-web-server/rest_portal/users/templates/users/base_template.html
<!DOCTYPE html>
<html lang="en">
  {% load staticfiles %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block description %}Administration panel{% endblock %}">
    <meta name="author" content="">
    {% block meta %}{% endblock %}
    <link rel="icon" href="{% static 'users/favicon.ico' %}">

    <title>{% block title %}Administration panel{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'users/bootstrap-3.2.0/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'users/custom-css/style.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'users:index' %}">SII Project</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'users:index' %}">Home</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">REST Interface <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header">Users</li>
				<li><a href="{% url 'users:restcredential' %}">User credentials</a></li>
				<li><a href="{% url 'users:restuserlevellist' %}">User levels</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Documents</li>
                <li><a href="{% url 'documents:listuserdocuments' %}">User documents</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav pull-right">
			{% if user.is_authenticated %}
			<li class="navbar-brand">User: {{ user }}</li>
			<li><a href="{% url 'users:logout' %}">Logout</a></li>
            {% else %}
			<li><a href="{% url 'users:login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="starter-template">
	  {% block content %}
	     <h1>Please, <a href="{% url 'users:login' %}">login</a> first.</h1>
	  {% endblock %}
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'users/bootstrap-3.2.0/js/bootstrap.min.js' %}"></script>
  </body>
</html>

server/django-web-server/rest_portal/users/templates/users/create_user.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Administration panel{% endblock %}

{% block content %}
        
        <form class="form-horizontal" method="post" action="{% url 'users:createuser' %}">
			{% csrf_token %}
			<fieldset>

			<!-- Form Name -->
			<legend>Personal credentials</legend>
			
		    {% if error_message %}
		    <h4>{{ error_message }}</h4>
		    {% endif %}
	
			<!-- Password input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="password">Your password*</label>
			  <div class="col-md-4">
				<input id="password" name="password" type="password" placeholder="Password" class="form-control input-md" required autofocus>
			  
			  </div>
			</div>
			
			<legend>Create new user</legend>
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newusername">Username*</label>  
			  <div class="col-md-4">
			  <input id="newusername" name="newusername" type="text" placeholder="username" class="form-control input-md" pattern="[a-zA-Z@.+-_]*" maxlength="30" required>
				
			  </div>
			</div>

			<!-- Password input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newpassword">Password*</label>
			  <div class="col-md-4">
				<input id="newpassword1" name="newpassword1" type="password" placeholder="password" class="form-control input-md" pattern=".{8,}" required>
				<span class="help-block">Must be at least 8 characters long</span> 
				
			  </div>
			</div>

			<!-- Confirm Password input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newpassword">Confirm Password*</label>
			  <div class="col-md-4">
				<input id="newpassword2" name="newpassword2" type="password" placeholder="password" class="form-control input-md" required>
				
			  </div>
			</div>
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newusername">First name</label>  
			  <div class="col-md-4">
			  <input id="newfirstname" name="newfirstname" type="text" placeholder="name" class="form-control input-md" maxlength="30">
				
			  </div>
			</div>
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newusername">Last name</label>  
			  <div class="col-md-4">
			  <input id="newlastname" name="newlastname" type="text" placeholder="surname" class="form-control input-md" maxlength="30">
				
			  </div>
			</div>

			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="textinput">Email</label>  
			  <div class="col-md-4">
			  <input id="newemail" name="newemail" type="email" placeholder="email" class="form-control input-md">
				
			  </div>
			</div>

			<!-- Select -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="userlevel">Security level</label>
			  <div class="col-md-4">
				<select id="newuserlevel" name="newuserlevel" class="form-control">
				  {% for lev in levels %}
				  <option value="{{ lev }}">Level {{ lev }}</option>
				  {% endfor %}
				</select>
			  </div>
			</div>
			
			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="submit"></label>
			  <div class="col-md-4">
				<button id="submit" name="submit" type="submit" class="btn btn-primary">Create</button>
			  </div>
			</div>

			</fieldset>
		</form>
		
{% endblock %}

server/django-web-server/rest_portal/users/templates/users/delete_user.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Administration panel{% endblock %}

{% block content %}
        
        <form class="form-horizontal" method="post" action="{% url 'users:deleteuser' %}">
			{% csrf_token %}
			<fieldset>

	{% if page == 'home' %}

			<!-- Form Name -->
			<legend>Delete current user (cannot delete superuser)</legend>
			
		    {% if message1 %}
		    <h4>{{ message1 }}</h4>
		    {% endif %}
			
			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="submit">Delete current user</label>
			  <div class="col-md-4">
				<button id="action" name="action" value="currentuser" class="btn btn-danger" {% if user.is_superuser %}disabled{% endif %}>Delete</button>
			  </div>
			</div>
			
			<legend>Delete another user (only superuser can do this)</legend>
			
		    {% if message2 %}
		    <h4>{{ message2 }}</h4>
		    {% endif %}

			<!-- Select Basic -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="selectbasic">Select user</label>
			  <div class="col-md-4">
				<select id="username" name="username" class="form-control" {% if not user.is_superuser %}disabled{% endif %}>
				  {% for u in userlist %}
				  <option value="{{ u }}">{{ u }}</option>
				  {% endfor %}
				</select>
			  </div>
			</div>
			
			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="submit">Delete selected user</label>
			  <div class="col-md-4">
				<button id="action" name="action" value="otheruser" class="btn btn-danger" {% if not user.is_superuser %}disabled{% endif %}>Delete</button>
			  </div>
			</div>
			
	{% elif page == 'confirmcurrent' %}
	
			<!-- Button (Double) -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="confirmdelete">Are you sure to delete your account?</label>
			  <div class="col-md-4">
				<button id="action" name="action" value="confirmdeletecurrent" class="btn btn-danger">Confirm</button>
				<button id="action" name="action" value="abortdeletecurrent" class="btn btn-primary">Cancel</button>
			  </div>
			</div>
			
			<input type="hidden" id="toremove" name="toremove" value="{{ toremove }}" />
	
	{% elif page == 'confirmother' %}
	
			<!-- Button (Double) -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="confirmdelete">Are you sure to delete {{ deluser }}?</label>
			  <div class="col-md-4">
				<button id="action" name="action" value="confirmdeleteother" class="btn btn-danger">Confirm</button>
				<button id="action" name="action" value="abortdeleteother" class="btn btn-primary">Cancel</button>
			  </div>
			</div>
			
			<input type="hidden" id="toremove" name="toremove" value="{{ deluser }}" />
	
	{% endif %}

			</fieldset>
		</form>
		
{% endblock %}

server/django-web-server/rest_portal/users/templates/users/home.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Administration panel{% endblock %}

{% block content %}
        
		<form class="form-horizontal">
			<fieldset>

			<!-- Form Name -->
			<legend>Administration</legend>
			
	{% if user.is_authenticated %}
			
		{% if not initialized %}
		
			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="init">Initialize system</label>
			  <div class="col-md-4">
				<a class="btn btn-lg btn-danger" href="{% url 'users:init' %}" role="button" {% if not user.is_superuser %}disabled{% endif %}>GO!</a>
			  </div>
			</div>
			
		{% else %}

			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="levels">Manage security levels</label>
			  <div class="col-md-4">
				<a class="btn btn-lg btn-danger" href="{% url 'users:levels' %}" role="button" {% if not user.is_superuser %}disabled{% endif %}>GO!</a>
			  </div>
			</div>
			
			<!-- Form Name -->
			<legend>User management</legend>
			
			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="init">Create new user</label>
			  <div class="col-md-4">
				<a class="btn btn-lg btn-success" href="{% url 'users:createuser' %}" role="button">GO!</a>
			  </div>
			</div>
			
			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="init">Delete an existing user</label>
			  <div class="col-md-4">
				<a class="btn btn-lg btn-success" href="{% url 'users:deleteuser' %}" role="button">GO!</a>
			  </div>
			</div>
			
			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="init">Manage security levels of user</label>
			  <div class="col-md-4">
				<a class="btn btn-lg btn-success" href="{% url 'users:userpermissions' %}" role="button">GO!</a>
			  </div>
			</div>
			
		{% endif %}
			
	{% else %}
			
			<h1>Please, <a href="{% url 'users:login' %}">login</a> first.</h1>
			
	{% endif %}

			</fieldset>
		</form>

        
{% endblock %}

server/django-web-server/rest_portal/users/templates/users/init_system.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Administration panel{% endblock %}

{% block content %}
        
		<form class="form-horizontal" method="post" action="{% url 'users:init' %}">
			{% csrf_token %}
			<fieldset>

			<!-- Form Name -->
			<legend>Initialize system</legend>
			
		    {% if error_message %}
		    <h4>{{ error_message }}</h4>
		    {% endif %}

			<!-- Password input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="password">Personal Password</label>
			  <div class="col-md-4">
				<input id="password" name="password" type="password" placeholder="Password" class="form-control input-md" required autofocus>
				
			  </div>
			</div>

			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="submit"></label>
			  <div class="col-md-4">
				<button id="submit" name="submit" type="submit" class="btn btn-primary">Initialize</button>
			  </div>
			</div>

			</fieldset>
		</form>
        
{% endblock %}

server/django-web-server/rest_portal/users/templates/users/logout.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block meta %}<meta http-equiv="refresh" content="5; url={% url 'users:index' %}" />{% endblock %}

{% block title %}Login page{% endblock %}

{% block content %}
        <h1>You are now logged out.</h1>
        <h2>You will be redirect within 5 seconds.<br /><a href="{% url 'users:index' %}">Click here</a> to go now.</h2>
{% endblock %}